<?php
return [
    'title' => '?? ???',
    'lead'  => '???? ??????? ????? ??????? ????? ?????.',
    'aboutus_lead' => '',
    'aboutus_title' => '',
    'client_bankmuscat_alt' => '',
    'client_chery_alt' => '',
    'client_ford_alt' => '',
    'client_hyundai_alt' => '',
    'client_lexus_alt' => '',
    'client_ooredoo_alt' => '',
    'client_rasalhamra_alt' => '',
    'company_anmat_description' => '',
    'company_anmat_feature_1' => '',
    'company_anmat_feature_2' => '',
    'company_anmat_feature_3' => '',
    'company_anmat_kicker' => '',
    'company_anmat_sub' => '',
    'company_anmat_tagline' => '',
    'company_anmat_title' => '',
    'company_ides_description' => '',
    'company_ides_feature_1' => '',
    'company_ides_feature_2' => '',
    'company_ides_feature_3' => '',
    'company_ides_kicker' => '',
    'company_ides_sub' => '',
    'company_ides_tagline' => '',
    'company_ides_title' => '',
    'company_seraj_btn' => '',
    'company_seraj_description' => '',
    'company_seraj_feature_1' => '',
    'company_seraj_feature_2' => '',
    'company_seraj_feature_3' => '',
    'company_seraj_kicker' => '',
    'company_seraj_sub' => '',
    'company_seraj_tagline' => '',
    'company_seraj_title' => '',
    'mission_text' => '',
    'stats_regions' => '',
    'stats_regions_label' => '',
];


